# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 12:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people_detail',
            name='created',
        ),
        migrations.AddField(
            model_name='people_detail',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 8, 17, 17, 40, 24, 695000), null=True),
        ),
    ]
