# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 17:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20170817_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people_detail',
            name='address',
        ),
        migrations.RemoveField(
            model_name='people_detail',
            name='registered_region',
        ),
        migrations.AlterField(
            model_name='people_detail',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 8, 29, 23, 11, 23, 872000), null=True),
        ),
    ]
